@url = http://localhost:5000
@bookId = 9d9ae4a6-46e6-41c8-b669-22bcd4e7960f
@authorId = 478658de-0f4e-4f11-bbcd-4917b8c177bb
@publisherId = d5c1eb83-5e9a-4973-b845-669ae60076f6

###
GET {{url}}/api/book

###
GET {{url}}/api/book/{{bookId}}

### 
GET {{url}}/api/author

### 
GET {{url}}/api/author/{{authorId}}

### 
GET {{url}}/api/publisher

### 
GET {{url}}/api/publisher/{{publisherId}}

###
POST {{url}}/api/book
Content-Type: application/json

{
  "title": "New book",
  "isbn": "9783161484100",
  "authorId": "{{authorId}}",
  "publisherId": "{{publisherId}}",
  "releaseDate": "2024-11-16"
}

###
POST {{url}}/api/author
Content-Type: application/json

{
  "firstName": "William",
  "lastName": "Shakespeare",
  "dateOfBirth": "1564-04-23"
}

###
POST {{url}}/api/publisher
Content-Type: application/json

{
  "name": "Expertia",
  "address": "342 Example St, Washington, WA",
  "foundedYear": 1995
}

###
PUT {{url}}/api/book/{{bookId}}
Content-Type: application/json

{
  "id": "{{bookId}}",
  "title": "Updated Book",
  "isbn": "1234567891234",
  "authorId": "{{authorId}}",
  "publisherId": "{{publisherId}}",
  "releaseDate": "2024-10-01"
}

###
PUT {{url}}/api/author/{{authorId}}
Content-Type: application/json

{
  "id": "{{authorId}}",
  "firstName": "FirstName",
  "lastName": "LastName",
  "dateOfBirth": "1980-05-10"
}

###
PUT {{url}}/api/publisher/{{publisherId}}
Content-Type: application/json

{
  "id": "{{publisherId}}",
  "name": "New publisher",
  "address": "231 Updated St, Washington, WA",
  "foundedYear": 2000
}

###
DELETE {{url}}/api/book/{{bookId}}

###
DELETE {{url}}/api/author/{{authorId}}

###
DELETE {{url}}/api/publisher/{{publisherId}}



